from fastapi import APIRouter, HTTPException
from fastapi.responses import RedirectResponse
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build

from .credentials import (
    CREDENTIALS_FILE,
    SCOPES,
    save_credentials,
    get_stored_credentials,
)
from config import settings


router = APIRouter(prefix="/auth", tags=["auth"])


# MVP in-memory OAuth flow storage.
#
# IMPORTANT:
# We store the SAME Flow object created during /login and reuse it
# during /callback. This keeps the PKCE code_verifier alive.
#
# In production, this should be stored securely using a session/database.
oauth_flows = {}


def get_flow():
    """Create a new Google OAuth flow."""
    if not CREDENTIALS_FILE.exists():
        raise HTTPException(
            status_code=500,
            detail=(
                "credentials.json not found. "
                "Please add it to the backend folder."
            ),
        )

    return Flow.from_client_secrets_file(
        str(CREDENTIALS_FILE),
        scopes=SCOPES,
        redirect_uri=settings.OAUTH_REDIRECT_URI,
    )


@router.get("/status")
def auth_status():
    """Check whether Gmail is currently connected."""
    creds = get_stored_credentials()

    if not creds or not creds.valid:
        return {
            "connected": False,
            "email": None,
        }

    try:
        service = build(
            "gmail",
            "v1",
            credentials=creds,
        )

        profile = service.users().getProfile(
            userId="me"
        ).execute()

        return {
            "connected": True,
            "email": profile.get("emailAddress"),
        }

    except Exception as e:
        print("AUTH STATUS ERROR:", repr(e))

        return {
            "connected": False,
            "email": None,
        }


@router.get("/login")
def login():
    """Start the Google OAuth login flow."""
    try:
        flow = get_flow()

        authorization_url, state = flow.authorization_url(
            access_type="offline",
            include_granted_scopes="true",
        )

        # Store the SAME Flow object using the OAuth state.
        # This preserves the PKCE code_verifier generated by the flow.
        oauth_flows[state] = flow

        print("OAUTH LOGIN STATE:", state)

        return {
            "auth_url": authorization_url,
        }

    except Exception as e:
        print("OAUTH LOGIN ERROR:", repr(e))

        raise HTTPException(
            status_code=500,
            detail=f"Failed to initialize OAuth flow: {e}",
        )


@router.get("/callback")
def auth_callback(state: str, code: str):
    """Handle Google's OAuth callback."""

    # Retrieve the exact same Flow object that was created
    # in /login.
    flow = oauth_flows.pop(state, None)

    if flow is None:
        raise HTTPException(
            status_code=400,
            detail=(
                "Invalid or expired OAuth state. "
                "Please start the Gmail connection again."
            ),
        )

    try:
        print("OAUTH CALLBACK STATE:", state)

        # Exchange authorization code for access/refresh tokens.
        #
        # Because we are using the SAME Flow object from /login,
        # its PKCE code_verifier is still available.
        flow.fetch_token(code=code)

        # Save Gmail credentials locally.
        save_credentials(flow.credentials)

        print("GMAIL AUTHENTICATION SUCCESSFUL")

        # Return to MailBrief dashboard.
        return RedirectResponse(url="/")

    except Exception as e:
        print("OAUTH CALLBACK ERROR:", repr(e))

        raise HTTPException(
            status_code=400,
            detail=f"Authentication failed: {e}",
        )